import React from 'react';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>React Yarn App</h1>
        <p>Built with Yarn package manager!</p>
        <p>Generated by Dockerfile Generator 🐳</p>
      </header>
    </div>
  );
}

export default App;

